### PR TITLE
Complete Linting Cleanup

### PR DESCRIPTION
**Pull request by amalnanavati**
# Description

This PR does a complete linting cleanup on the `ada_feeding` repo (including `ada_feeding_perception` and `ada_feeding`). Specifically, it includes the following changes:
1. Adds a `.pylintrc` and modifies the pull request template with more specific instructions on running pylint with that file. (**Note**: Because Github only looks in `main` for pull request templates, this was in a [commit to `main`](https://github.com/personalrobotics/ada_feeding/commit/48a0ecac815cadca9515bc62e202e6033c115f4a) that is not in this PR.)
2. Addresses **every single `pylint` warning or error** (based on `.pylintrc`) in this repository, except for the two `fixme` warnings (to indicate a comment with the word "TODO" in it).

# Testing procedure

Because these changes touch every part of the code, it is crucial to re-test every part of the code. Therefore, we run the following tests:

- [x] Test the Planning Scene: Run `ros2 launch ada_moveit demo.launch.py sim:=mock` and `ros2 launch ada_feeding ada_feeding_launch.xml` and verify that the planning scene that shows up in RVIZ matches the screenshots from #39 .
- [x] Test **every single tree** in `ada_feeding` (I did this with MoveIt in `sim:=mock`):
    - [x]  **MoveToDummyTree**: `ros2 action send_goal /AcquireFood ada_feeding_msgs/action/AcquireFood "{header: {stamp: {sec: 0, nanosec: 0}, frame_id: ''}, detected_food: {roi: {x_offset: 0, y_offset: 0, height: 0, width: 0, do_rectify: false}, mask: {header: {stamp: {sec: 0, nanosec: 0}, frame_id: ''}, format: '', data: []}, item_id: '', confidence: 0.0}}" --feedback`
    - [x]  **MoveToConfigurationTree**: `ros2 action send_goal /MoveAbovePlate ada_feeding_msgs/action/MoveTo "{}" --feedback`
    - [x]  **MoveToConfigurationWithPosePathConstraintsTree**: (Note: run the action server for`/MoveToRestingPosition` before this) `ros2 action send_goal /MoveToMouth ada_feeding_msgs/action/MoveTo "{}" --feedback`
    - [x]  **MoveToPoseTree**: (Note: run the action server for`/MoveToRestingPosition` before this) `ros2 action send_goal /TestMoveToPose ada_feeding_msgs/action/MoveTo "{}" --feedback`
    - [x]  **MoveToPoseWithPosePathConstraintsTree**: (Note: run the action server for`/MoveToRestingPosition` before this) `ros2 action send_goal /TestMoveToPoseWithPosePathConstraints ada_feeding_msgs/action/MoveTo "{}" --feedback`
- [x] Test the watchdog in isolation (and the dummy FT sensor): follow instructions in the [README](https://github.com/personalrobotics/ada_feeding/tree/amaln/cleanup/ada_feeding).
- [x] Test SegmentFromPoint. See Options in the [README](https://github.com/personalrobotics/ada_feeding/tree/amaln/cleanup/ada_feeding_perception).
    - [x] Option A
    - [x] Option B
    - [ ] [EDIT: I deprecated this because it is non-trivial to make it work with the depth images that SegmentFromPoint now requires] Option C
    - [x] Option D

# Before opening a pull request
- [x] Format your code using [black formatter](https://black.readthedocs.io/en/stable/) `python3 -m black .`
- [x] Run your code through [pylint](https://pylint.readthedocs.io/en/latest/) and address all warnings/errors. The only warnings that are acceptable to not address is TODOs that should be addressed in a future PR. From the top-level `ada_feeding` directory, run: `pylint --recursive=y --rcfile=.pylintrc .`.

# Before Merging
- [x] `Squash & Merge`

### CODE REVIEW

**Comment by amalnanavati** [comment]
PR is now ready for review. I ran all the above tests on LoveLace. All were in sim except for the SegmentAnything tests, since that requires the actual depth stream from the RealSense.

**Comment by amalnanavati** [comment]
One of the few non-linting changes I made was having `create_action_servers.py` pass the actual action type to the trees, as opposed to passing the string of the action type. None of the trees used the string (other than converting it into a type)

**Review by egordon — APPROVED** [review]
Not too rigorous of a review (in part because it is 90% linting), and I trust the testing procedure. action_type is a good change. Fine to merge and work on other PRs.

**Review by taylorkf — APPROVED** [review]
Also not too rigorous of a review given the extensive testing, but this all looks good.

**Pull request merged**
