### PR TITLE
Ada feeding perception code

### PR DESCRIPTION
**Pull request by BernieZhu**
Add codes and documents related to perception.

### CODE REVIEW

**Comment by amalnanavati** [comment]
@BernieZhu FYI I rebased this onto `ros2-devel`, which is the branch that this should get merged onto. Therefore, you should make sure to pull from this branch before making any future changes.

**Review by amalnanavati — CHANGES_REQUESTED** [review]
@BernieZhu It seems like the files in `test/food_imgs/...` aren't pushed, which makes it hard to recreate your tests. Could you push those images, or at least the ones you refer to in the README?

**Comment by BernieZhu** [comment]
Updates:
1. Add a function to remove the non-connected parts of the mask.
2. Add test images. Please unzip ada_feeding/ada_feeding_perception/test/food_img.zip before running the tests.
3. Remove redundant output of segmentation. Now it only provides the candidate with the highest score. Change number_output to show more.
4. Test_sam.py now shows the point you input on the image first.

**Comment by amalnanavati** [comment]
Closed with #24

**Pull request closed without merging**
