### PR TITLE
Implement Collision Meshes

### PR DESCRIPTION
**Pull request by amalnanavati**
# Description

This PR, building off of #38 , does the following:
1. Added STL messages of the wheelchair, table, head, and wheelchair collision area (expanded from the wheelchair to account for the human's body). All are based on [pr_assets (branch: `amaln/fix_wheelchair_arm`)](https://github.com/personalrobotics/pr_assets/tree/amaln/fix_wheelchair_arm/data/furniture), with some filetype conversions.
2. Added a generic `ada_planning_scene.py` node that takes parameters specifying STL meshes and their poses, and populates the planning scene with those meshes.

Screenshot 2023-07-20 at 8 50 38 PM
Above: An image of the entire planning scene.

Screenshot 2023-07-20 at 8 55 26 PM
Above: An image of the planning scene without the expanded wheelchair collision area.

# Design Decisions
- The way MoveIt works, the planning scene is stored on the MoveIt server, not in individual clients. Therefore, it doesn't make sense to populate the planning scene as a behavior in the behavior tree, since that would unnecessarily repeatedly populate it. Hence, I implemented `ada_planning_scene.py` as a separate node.
- During the course of robot-assisted feeding, we will need to modify the planning scene in at least two instances: (1) updating the head pose based on face detection; and (2) disabling collisions with `wheelchair_collision.stl` (the expanded wheelchair) during the final approach to the mouth. These both can be handled within py_tree behaviors: (1) by [publishing a `MOVE` message to `/collision_object`](https://github.com/ros-planning/moveit_msgs/blob/master/msg/CollisionObject.msg) with the ID of the face; and (2) utilizing ROS2 services to update the allowed_collision_matrix to enable/disable collisions for a particular object (see the [`amaln/allowed_collision_matrix` branch of the PRL fork of pymoveit2](https://github.com/personalrobotics/pymoveit2/tree/amaln/allowed_collision_matrix)). Hence, this node does not need to expose any API for updating the meshes; that can be done by the behaviors directly.

# Testing procedure

I did all the below testing in sim, although I also include initialization instructions to test it on the real robot.

**Initialization**:
1. Launch MoveIt:
    1. Real Robot: `ros2 launch ada_moveit demo.launch.py`
    2. Sim: `ros2 launch ada_moveit demo.launch.py sim:=mock`
2. Launch the F/T sensor:
    1. Real Robot: `ros2 run forque_sensor_hardware forque_sensor_hardware --ros-args -p host:=xxx.xxx.x.xx` (replace the x's with the correct IP)
    2. Sim: `ros2 run ada_feeding dummy_ft_sensor.py`
3. Launch the feeding nodes: `ros2 launch ada_feeding ada_feeding_launch.xml`

**Testing**:
- [x] Visually verify that the planning scene mirrors our ADA setup.
- [x] Verify that all the `MoveTo...` actions still work:
    - [x] `ros2 action send_goal /MoveAbovePlate ada_feeding_msgs/action/MoveTo "{}" --feedback`
    - [x] `ros2 action send_goal /MoveToRestingPosition ada_feeding_msgs/action/MoveTo "{}" --feedback`
    - [x] `ros2 action send_goal /MoveToStowLocation ada_feeding_msgs/action/MoveTo "{}" --feedback`
    - [x] `ros2 action send_goal /MoveToMouth ada_feeding_msgs/action/MoveTo "{}" --feedback`

# Before opening a pull request
- [x] Format your code using [black formatter](https://black.readthedocs.io/en/stable/) `python3 -m black .`
- [x] Run your code through [pylint](https://pylint.readthedocs.io/en/latest/) and address (most) warnings/errors: `pylint --recursive=y .`

# Before Merging
- [x] `Squash & Merge`

### CODE REVIEW

**Comment by amalnanavati** [comment]
NOTE: There may be a bug where moving to a "staging location" pose/configuration with orientation constraints to keep the fork straight (e.g., `MoveToMouth`, `TestMoveToPoseWithPosePathConstraints`) doesn't work when the `wheelchair_collision` mesh is in the scene. I'll look more into this.

**Comment by amalnanavati** [comment]
It turned out that the issue was `allowed_planning_time` -- with the wheelchair collision mesh in the planning scene (as well as the other goal and orientation constraints), 0.5 sec was not always long enough to complete the "move to staging location" call. Hence, I added the ability to set the allowed planning time by parameter, which addressed the issue.

**Comment by amalnanavati** [comment]
Also adjusted `wheelchair_collision.stl` to account for breasts.

Screenshot 2023-08-01 at 5 38 18 PM

**Review by taylorkf — APPROVED** [review]
Running this required me to separately install trimesh (https://trimsh.org/), but otherwise everything seems to be documented well and working properly

**Pull request merged**
